import subprocess

def run_wingman_create_file(path, content, message=None):
    cmd = ["python3", "Wingman/Tools/git_wingman.py", "create_file", "--path", path]
    if message:
        cmd.extend(["--message", message])
    cmd.extend(["--content", content])
    subprocess.run(cmd, check=True)

sections = [
    ("Hard Turn or Break", """a. Estimate range and angle off of the attacking aircraft.\nb. Call a hard turn if your opponent is 2000' or more and 30° or more angle off. (Hard turn is a near maximum performance maneuver with visual control of situation.)\nc. Call a “break” if the aircraft is within 2000' and at a low angle off, less than 30°. (“Break” is an emergency maneuver requiring immediate action without regard for visual sighting of opponent.)\nd. Use rudder leading into turn as this will tend to slow you down and also tighten your turn. In other words, you will hasten a speed differential and thus force your opponent to the outside, gaining lateral separation.\ne. If your opponent is within break range but with excessive closing speed, it might not be necessary to use a maximum performance turn to force him to the outside. Remember, when on the defensive, your first concern is to gain lateral separation. However, try and save part of your airspeed for future maneuvering."""),
    ("Scissors Maneuver", """a. Reverse and pull your nose up and into your opponent when he slides to the outside on your hard turn or break. Repeat this reversal each time your opponent slides through your flight path to the outside.\nb. Use rudders to obtain maximum performance on reversing each turn of the scissors.\nc. Use all power available to reduce your stall speed to its lowest.\nd. Keep speed brakes in so as to gain and hold a high position. You can use them if you are sliding to your opponent’s 6 o’clock position and want to drop down without over-running.\ne. Use flaps at most desirable lift position to help reduce stall speed, and elevate the nose of your aircraft.\n  - This can be an insidious move if used at the proper time.\n  - Be sure and know your allowable airspeed for various flap positions.\nf. If your opponent ends up on top during the scissors, try to place yourself in phase with and directly underneath him before he starts sliding to your 6 o’clock position.\n  - This will tend to give your opponent a visual disadvantage with the subsequent possibility of his over-controlling and stalling, or mis-maneuvering in attempting to find you.\n  - A stall would tend to force him to settle and slide forward.\n> **Remember** - The airspeed up to the point of stall is less than after the stall occurs (if the aircraft is not in an excessive nose high altitude), so use smooth trim and rudder technique to get the most out of the aircraft at slow airspeed.\ng. If you should get your opponent in a vertical scissors by forcing him to the outside in a descending break, reduce your power, extend your brakes and drop your flaps (if slow enough) to try and force your opponent below and in front of you.\nh. The decision on when to scissor an opponent will depend upon how rapidly he is sliding to the outside of the turn and how far behind he is as he slides through your flight path. Keep your opponent in sight as much as possible - a reverse too early will be to his advantage."""),
    ("High Speed Yo-Yo", """(Assume you are closing rapidly on an opponent)\na. Slide high and to the rear of your opponent when you are no longer able to stay in his turn radius. Trade your airspeed for altitude and therefore diminish your turn radius. Maintain your advantage by going high at 6 o’clock. Avoid waiting until the last possible moment to Yo-Yo off an opponent. He may pull or break up into you and force you on the defensive.\nb. Try to slide back down to your opponent’s 6 o’clock position. Use speed brakes and power reduction as necessary to help prevent overshooting.\nc. If you should slide down at too great an angle off, your opponent may pull up into you thus forcing you below and in front.\nd. In this case roll one-quarter away from your opponent and pull up with him the moment he has committed himself (to keep him in sight and get on top).\ne. Otherwise spiral or dive away to open up the distance as most likely the angle off will be too great and your opponent will end up on top."""),
    ("Low Speed or Inside Yo-Yo", """(Assume you have placed yourself at the 6 o’clock low position on your opponent and are unable to pull lead at a low airspeed.)\na. Slide to the inside by dropping your nose. Try not to burble the aircraft. This will allow you to close on him by increasing your airspeed and cutting to the inside.\nb. Shallow out your turn and slide up to the 6 o’clock position when you reach about 45° - 35° from line abreast. This will position you somewhat closer to your opponent and reduce your lead requirement. You may have to repeat this a few times to position yourself correctly.\n**Remember**: Your opponent can cancel you out by doing likewise or by making a hard break into you on your upswing toward his 6 o’clock position."""),
    ("Diving Spiral", """a. Lower your nose and start a descending turn. Pull as many “G’s” as the situation warrants. This is to prevent your opponent from tracking you.\nb. Avoid an excessively nose low altitude, as this will make you easier to track. However, dive steep enough to maintain the airspeed necessary to pull maximum “G’s”."""),
    ("Spiral for Airspeed", """(Assume an opponent Yo-Yo’s or slides to the outside, but not far enough forward for you to reverse into him.)\na. Wait until your opponent has about reached the apex of his Yo-Yo or has slid well to the outside.\nb. Reduce some of your “G’s” and spiral down 180° away from your opponent. Relax more and more “G’s” as the distance opens up and your opponent is out of effective range (about 4000'). Only reduce enough “G’s” initially to accelerate away from your opponent and at the same time keep part of your lateral separation."""),
    ("High “G” Barrel Roll", """a. Initiate a hard turn or break to get lateral separation, or use the diving spiral and reduce power to obtain lateral separation.\nb. Reverse and barrel roll in the opposite direction without releasing your “G’s”. Come in with top rudder when coming down the opposite side of roll to prevent dish out and also to flatten out your roll.\nc. Fly the aircraft on the “burble” all the way around the roll. This will slow you down, tighten your roll and tend to force your opponent to overshoot.\nd. Look for your opponent high and from the direction of the roll. He will normally slide below and forward from that position if he overshoots.\n**Caution**: Try to keep opponent in sight at all times as he may pull high out of the roll and wait for you to complete it before coming in again."""),
    ("Hammer Turn", """(Assume you are at a slow airspeed, nose high altitude with an opponent out of phase or at a distance behind - around 4000')\na. Rudder the aircraft around the top, stick to the rear. Pull your nose through the horizon toward and approximately in line with your opponent’s nose.\nb. See if your opponent tries to cut you off or fly the same relative flight path you described. If he cuts you off, your chances on getting him out of phase are much better, therefore -\nc. Roll into your opponent to increase his angle off and initiate a sharp pull up out of your descent to force your opponent below and possibly in front.\nd. If you retard your throttle and drop a few degrees of flaps (at low A/S) you will flatten out your descent and thus greatly insure the possibility of your opponent’s overshoot.\ne. When flying through all these maneuvers, use good rudder technique along with proper trim. This will insure your getting the most out of the aircraft when it is necessary. Also, learn how to use speed brakes and power reduction when most advantageous to gain your desired position.""")
]

base_path = "Works of John Boyd/A Proposed Plan for Fighter vs Fighter Training"
html_template = """<!DOCTYPE html>
<html>
<head>
<title>Mission: {name}</title>
</head>
<body>
<h1>Mission: {name}</h1>
<p>Placeholder for game mission to be developed.</p>
</body>
</html>"""

for name, content in sections:
    sanitized_name = name.replace(' ', '_').replace('“', '').replace('”', '')
    txt_path = f"{base_path}/{sanitized_name}.txt"
    html_path = f"{base_path}/Mission_{sanitized_name}.html"
    
    run_wingman_create_file(txt_path, content, f"Create text file for {name}")
    run_wingman_create_file(html_path, html_template.format(name=name), f"Create HTML placeholder for {name}")

print("All files created successfully.")
